# Site settings
title: "Syrion"
bye_message: "Syrion © 2021 "
baseurl: ""
url: "https://syrion.me"
disqus: syrion89

# Header settings
nick: "syrion89"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "syrion89"
blog:
    server: "wordpress.com"
    nick: "syrion89"
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
