# Site settings
title: "gjuniioor"
bye_message: "Thx!"
baseurl: "/"
url: "https://syrion89.github.io"
disqus: syrion89

# Header settings
nick: "syrion89"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "syrion89"
blog:
    server: "wordpress.com"
    nick: "syrion89"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
